#define CONFIG_VERSION_MAJOR 1
#define CONFIG_VERSION_MINOR 0
#define CONFIG_VERSION_ALTER 0

/* #define MAPLELEAF_SCENE_DEBUG 0 */
/* #define MAPLELEAF_RENDERSTAGE_DEBUG 0 */
/* #define MAPLELEAF_PIPELINE_DEBUG 0 */
/* #define MAPLELEAF_SHADER_DEBUG 0 */
#define MAPLELEAF_VALIDATION_DEBUG 1
/* #define MAPLELEAF_DEVICE_DEBUG 0 */
/* #define MAPLELEAF_DESCRIPTOR_DEBUG 0 */
/* #define MAPLELEAF_GRAPHIC_DEBUG 0 */
/* #define MAPLELEAF_GPUSCENE_DEBUG 0 */

/* #define STEREORENDERING 0 */
